### ISSUE TITLE
Outdated vscode extension

### ISSUE THREAD

**Issue by luiz290788** [fwcd/kotlin-language-server#155]
I've realised that the vscode extension present on the marketplace is outdated. The latest version there is 0.2.5
<img width="471" alt="Screen Shot 2019-08-27 at 1 49 42 pm" src="https://user-images.githubusercontent.com/707366/63739708-94b32800-c8d1-11e9-9e27-7f51eab0ec2e.png">

Is the extension not being maintained anymore?

I am interested in helping in this project to use koltin in VSCode. Where is the best place to start?

**Comment by fwcd** [comment]
The VSCode extension no longer bundles the language server in the extension package, instead it auto-downloads the latest GitHub release, which is [0.3.0](https://github.com/fwcd/kotlin-language-server/releases). Versions are thus updated independently and both extension and language server are still being maintained.

If you are interested in contributing, I would recommend you to take a look here: https://github.com/fwcd/kotlin-language-server/pull/141#issuecomment-518749312

**Comment by luiz290788** [comment]
Thanks for the response!

**Comment by LifeIsStrange** [comment]
It would be really nice to add an option to auto download latest master instead of latest stable releases.
