### ISSUE TITLE
Language Server no longer starting

### ISSUE THREAD

**Issue by fwgreen** [fwcd/kotlin-language-server#170]
<img width="319" alt="Screen Shot 2019-10-26 at 11 44 55 PM" src="https://user-images.githubusercontent.com/7098161/67629351-ac177e80-f84a-11e9-9b8b-20d604d022a7.png">
I removed the plugin after removing the server from Application Support, and found this message in the developer tools after a complete reinstall:

```
Activating extension 'fwcd.kotlin' failed: Internal error..
```

macOS 10.15
OpenJDK 13
VS Code 1.39.2

**Comment by jasonvalenzuela** [comment]
@fwgreen I also had a similar issue on macOS 10.15 with Vim, and I was able to resolve it by giving iTerm (where I was running Vim) Full Disk Access in the Security & Privacy settings. You will likely need to give VSCode those permissions as well. Here is the SO answer that helped me: https://apple.stackexchange.com/a/341967
