### ISSUE TITLE
Kotlin extesion internal error

### ISSUE THREAD

**Issue by lin182** [fwcd/kotlin-language-server#177]
![image](https://user-images.githubusercontent.com/6075020/70761997-73156980-1d25-11ea-9cae-5d5aa8271b60.png)

**Comment by fwcd** [comment]
Could you post the log from the Kotlin extension in the `Output` tab?

**Comment by lin182** [comment]
I'm sorry, the location of my project has blank spaces: "Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 38: file:///d:/Programing/Proyectos/Visual Studio Code/Spring/Udemy/Ejemplo1/demo", I already have it solved
