### ISSUE TITLE
Implement JDT.LS extension for Kotlin files

### ISSUE THREAD

**Issue by fwcd** [fwcd/kotlin-language-server#192]
### Addresses #4

The [JDT language server](https://github.com/eclipse/eclipse.jdt.ls) can be extended to support custom project importers. Since Kotlin symbols cannot currently be referenced inside Java source files, we could provide such an extension in a subproject inside this repo with an importer that locates and registers Kotlin source files in the JDT's project model.

Implementation notes:
* A list of JDT.LS extension points can be found [here](https://github.com/eclipse/eclipse.jdt.ls/blob/3ab2fdf3baceb8c9dde89a265f8a3596a851bce0/org.eclipse.jdt.ls.core/plugin.xml)
* An example JDT.LS extension can be found [here](https://github.com/gorkem/jdt.ls.pde)
    * Note how the VSCode extension [contains a custom contribution point](https://github.com/gorkem/jdt.ls.pde/blob/e814773c5d8ba98d2c8e6ea9dbfa89ac10e13eab/vscode-pde/package.json#L21-L53) for `javaExtensions`
* The JDT.LS importer should have a higher precedence that the default ones (see https://github.com/eclipse/eclipse.jdt.ls/issues/480#issuecomment-349410925)
* The importer could use the same class path/source path resolvers as the language server, possibly by sharing their implementations through the `shared` subproject
* See also: https://github.com/eclipse/eclipse.jdt.ls/issues/449, https://github.com/redhat-developer/vscode-java/issues/531

**Comment by jonathanmarvens** [comment]
@fwcd Is this currently being implemented? The __VS Code__ __Java__/__Kotlin__ interoperability story is pretty frustrating at the moment, so I appreciate your efforts on this!

**Comment by guidovalli** [comment]
news about this?

**Comment by oscarsan** [comment]
Any news about this? :-), about to change from intelliJ to visual studio, this is the only thing that is stopping me.
