### ISSUE TITLE
Missing Arrow Syntax Highlighting

### ISSUE THREAD

**Issue by eyemotif** [fwcd/kotlin-language-server#195]
When using the arrow (i.e., `->`) for `when` branches, only the `-` is highlighted. In fact, neither the "greater than" or "less than" sign are highlighted like an operator in any environment.

**Comment by kerkmann** [comment]
What do you mean "it's not highlighted".
As I know, code highlighting is not in the scope of any language server.

Could you describe more, what you mean. :)
Which IDE are you using with which plugin?

I tried the following code and it's working without any problems. :)
```kotlin
val x = 1
when (x) {
    1 -> print("x == 1")
    2 -> print("x == 2")
    else -> { // Note the block
        print("x is neither 1 nor 2")
    }
}
```

**Comment by RenFraser** [comment]
@fwcd is this issue the job of tree-sitter-kotlin? If so, can we close this issue?

**Comment by fwcd** [comment]
> is this issue the job of tree-sitter-kotlin?

Assuming it is about the TextMate grammar used by the VSCode extension, no, since the TM grammar is hosted in this repo
