### ISSUE TITLE
Java Source Files side by side question

### ISSUE THREAD

**Issue by koush** [fwcd/kotlin-language-server#212]
It is common for projects to have both java and kotlin source files. I've noticed that the kotlin language server does not recognize java source files within the project. Unresolved errors. Is this just an issue with my project?

My brief investigation of dependency resolution is that java dependencies do work via checking gradle dependencies, etc. But I was unable to determine if they work within the same project.

**Comment by koush** [comment]
Found a related commit that indicates it should work?
https://github.com/fwcd/kotlin-language-server/pull/190

**Comment by fwcd** [comment]
Importing Java code into Kotlin within the same project should work (e.g. having `src/main/java` and `src/main/kotlin`). You might need to reload the language server after adding new Java files though. Are you using the latest version of the language server?

**Comment by koush** [comment]
I use the release extension. I also tested with my own build of the language server when addressing another issue.

Let me double check the path. Old android projects put both java and kotlin files into src/ (no main/java or main/kotlin). I'll update and see if it resolves.

**Comment by koush** [comment]
Before restructuring, I just reloaded the language server and it seems to be fixed. Maybe I had an older custom build running on accident.
