### ISSUE TITLE
Can't compile the language server

### ISSUE THREAD

**Issue by vorner** [fwcd/kotlin-language-server#232]
Hello

I'm following the `BUILDING.md` documentation. But when I type the recommended `./gradlew :server:installDist`, I get this error:

```

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'kotlin-language-server'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find net.coacoas.gradle:ensime-gradle:0.3.0-SNAPSHOT.
     Searched in the following locations:
       - file:/home/vorner/.m2/repository/net/coacoas/gradle/ensime-gradle/0.3.0-SNAPSHOT/maven-metadata.xml
       - file:/home/vorner/.m2/repository/net/coacoas/gradle/ensime-gradle/0.3.0-SNAPSHOT/ensime-gradle-0.3.0-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/net/coacoas/gradle/ensime-gradle/0.3.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/net/coacoas/gradle/ensime-gradle/0.3.0-SNAPSHOT/ensime-gradle-0.3.0-SNAPSHOT.pom
       - https://jcenter.bintray.com/net/coacoas/gradle/ensime-gradle/0.3.0-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/net/coacoas/gradle/ensime-gradle/0.3.0-SNAPSHOT/ensime-gradle-0.3.0-SNAPSHOT.pom
       - https://plugins.gradle.org/m2/net/coacoas/gradle/ensime-gradle/0.3.0-SNAPSHOT/maven-metadata.xml
       - https://plugins.gradle.org/m2/net/coacoas/gradle/ensime-gradle/0.3.0-SNAPSHOT/ensime-gradle-0.3.0-SNAPSHOT.pom
     Required by:
         project :
```

It seems it's using some non-existing dependency. Where do I get it?

(Note: I'm not experienced with anything JVM related, I just need to interact with some kotlin code and hoped to make my life a bit easier, so maybe I'm missing something others consider obvious)

**Comment by fwcd** [comment]
It seems to build fine in CI. Could you try recloning the repository and making a clean rebuild?

**Comment by vorner** [comment]
I've managed to successfully build inside a clean docker.

But if I do `git clean -xdf` and try it on current master on my main system, I still get this error (it's gentoo).

Is there some other cache I might clean?

**Comment by themkat** [comment]
Closing as this issue is quite old, and versions have changed a bit since them. No new similar issues have been reported. Please let me know if it should be reopened 🙂 


For people who want another option than above, you could also try deleting your Gradle caches. They usually reside in the `.gradle/caches` directory in your home directory.
