### ISSUE TITLE
Checking $PATH should also respect directories

### ISSUE THREAD

**Issue by daphil19** [fwcd/kotlin-language-server#255]
The `$PATH` environment variable supports directories; meaning an executable that's a direct (i.e, non-recursive) child of the directory is counted as in the `$PATH`. The language server should check if an entry is a directory and check it's children.

When coupled with #254, this results in the kotlin compiler & stdlib not being found, resulting in a failed build.

**Comment by msoucy** [comment]
I think the phrase that will help explain this is "relative path"

**Comment by daphil19** [comment]
Looking closer into this, I realized I was mistaken. The issue I was having was related to homebrew for linux's kotlin installation.

 I'll close this ticket and open a new one describing the homebrew situation
