### ISSUE TITLE
Launch mechanisms

### ISSUE THREAD

**Issue by pajatopmr** [fwcd/kotlin-language-server#261]
A question: 
Currently, KLS is used to test a Kotlin SDK (the client) by launching via stdio which takes about 3 seconds minimum (as near as I can tell).

Is there a KLS launch mechanism that can be used in client testing that will significantly improve on this 3 second baseline?

btw, if there is a better forum for asking questions such as this one, please do inform me. There is a Slack workspace "community-lsp.slack.com" with a kotlin-language-server channel that can be used fwiw.

**Comment by fwcd** [comment]
Dependency resolution is usually the bottleneck, depending on the project's build system it might always take a few seconds to spin up a Maven/Gradle JVM.

**Comment by fwcd** [comment]
Regarding a forum, I have seen that GitHub now offers an integrated discussions page which might be a good place for these kinds of questions, alternatively there is the KLS Discord server.

**Comment by pajatopmr** [comment]
I have tried the Discord server and got decent traction early on. After JetBrains announced LSP support is not happening, the Discord server seems to have entered radio silence mode. I like the idea of leveraging the GitHub discussions page as it localizes things KLS so I'll give that a shot and carry on this discussion of decreasing testing time when using KLS.

**Comment by fwcd** [comment]
Note that the Discord server is not affiliated with JetBrains in any way, just like this language server. It is a pure community project and always has been.
