### ISSUE TITLE
Current version

### ISSUE THREAD

**Issue by pajatopmr** [fwcd/kotlin-language-server#269]
Couple of questions:

1) How can I find the current version for a running instance of KLS?

2) How can I become aware of new releases?

**Comment by fwcd** [comment]
The latest GitHub release is what the VSCode extension uses, that should always be a somewhat stable version of the language server.

**Comment by fwcd** [comment]
Also, the version is not tracked by the language server itself since LSP has no notion of a 'version', instead, a client-specific extension should track the language server's version. For details, you might want to take a look at [the VSCode extension's server updater](https://github.com/fwcd/vscode-kotlin/blob/master/src/serverDownloader.ts).

**Comment by pajatopmr** [comment]
I believe the LSP does have a notion of server version. From the spec (3.16):
interface InitializeResult {
	/**
	 * The capabilities the language server provides.
	 */
	capabilities: ServerCapabilities;

	/**
	 * Information about the server.
	 *
	 * @since 3.15.0
	 */
	serverInfo?: {
		/**
		 * The name of the server as defined by the server.
		 */
		name: string;

		/**
		 * The server's version as defined by the server.
		 */
		version?: string;
	};
}

**Comment by fwcd** [comment]
Ah, that's interesting, I did not know about that, thanks! 012e7a8 adds support for `ServerInfo` and also logs the KLS version at launch.

**Comment by pajatopmr** [comment]
Great. Glad to be helpful. That takes care of the first question. How about the second one, do you publish notifications about new releases?

**Comment by fwcd** [comment]
As mentioned, new releases are published via GitHub releases. Depending on how you want to be notified, you could either [visit the page manually](https://github.com/fwcd/kotlin-language-server/releases), [query the API with a script](https://api.github.com/repos/fwcd) or watch the repository to get an email notification:

![image](https://user-images.githubusercontent.com/30873659/109405273-f04eed80-796e-11eb-9bed-cfb3b201ec4d.png)

**Comment by pajatopmr** [comment]
Thanks, watching the repo works for me.
