### ISSUE TITLE
Package name completion

### ISSUE THREAD

**Issue by fwcd** [fwcd/kotlin-language-server#28]
Automatically suggest the correct package name with code completion when creating a new Kotlin file.

**Comment by fwcd** [comment]
For reference, this is how the Java language server implements this:

https://github.com/eclipse/eclipse.jdt.ls/blob/2a01577832353daed03dec79ee9b59db9deb28de/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java#L97-L101

**Comment by ryansobol** [comment]
Hrm, it's not obvious to me how this function would accept a `CompiledFile` and a `Cursor` and produce a `CompletionList` with a relevant package name at the head.

**Comment by kerkmann** [comment]
Created pull requests, maybe there is a beautifuller way. :)
https://github.com/fwcd/kotlin-language-server/pull/207

**Comment by kerkmann** [comment]
This issue can be closed, already merged in #207
