### ISSUE TITLE
Warnings during fresh install of 1.1.1

### ISSUE THREAD

**Issue by pajatopmr** [fwcd/kotlin-language-server#282]
There is a pair of warnings in the following output generated by building and running a fresh KLS clone on macos(Catalina) using openjdk14.0.2. The build was a command line build: ./gradlew :server:installDist in which no problems were reported. The first set of messages appear to be a Kotlin, Gradle or JDK issue.  The second pertains to SLF4J. Can't say if these are related or not. And it seems like the first set has been around a while and the second is something new.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil (file:/Users/pmr/IdeaProjects/clones/kls-1.1.1/kotlin-language-server/server/build/install/server/lib/kotlin-compiler-1.4.30-RC-232.jar) to method java.util.ResourceBundle.setParent(java.util.ResourceBundle)
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Content-Length: 139

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"main      Adding script definitions [ScriptTemplateWithArgs]"}}Content-Length: 126

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"main      Kotlin Language Server: Version 1.1.2"}}Content-Length: 108

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"main      Connected to client"}}

**Comment by fwcd** [comment]
The first warning is an upstream issue: https://youtrack.jetbrains.com/issue/KT-43520

The SLF4J warning is harmless, essentially just a small notice that some upstream library uses SLF4J and we won't get any log messages from there. If, at some point, we decide to migrate to SLF4J, this should go away as well.
