### ISSUE TITLE
Add a linter to the language server code itself

### ISSUE THREAD

**Issue by daplf** [fwcd/kotlin-language-server#304]
As far as I can tell, we're not linting the language server code itself. Perhaps it would be interesting to add this (and add it to the PR builds as well). It would probably make the code a lot cleaner, making it easier to contribute. What do you think?

As for what linter to choose from, suggestions would be welcome, but I suppose we could use `ktfmt` since it's what we're using to format client code.

**Comment by fitrh** [comment]
How about [ktlint](https://github.com/pinterest/ktlint) ?

**Comment by rami3l** [comment]
@fitrh 
We are in some sort of an awkward situation right now, as @fwcd just made the move from `ktlint` to `ktfmt` in https://github.com/fwcd/kotlin-language-server/pull/238.
Also, it seems to me that the project is neither coherently formatted nor linted, which worries me even more...

**Comment by themkat** [comment]
Let's consider this closed by #422
