### ISSUE TITLE
Running Kotlin file without class

### ISSUE THREAD

**Issue by dvanderleij** [fwcd/kotlin-language-server#321]
### Motivation
In IntelliJ I can run a Kotlin file that does not have a class: e.g. a file named `Main.kt`
```
fun main() {
    println("hello World")
}
```

(No enclosing class)

### Description
I would like to see a run/debug button just like in Java in VScode above this main function to run this.
<img width="362" alt="image" src="https://user-images.githubusercontent.com/8983861/144199589-b6d26ca6-a8d7-4f7c-98fc-6bd4f83a297f.png">

### Alternatives considered
Using IntelliJ, creating a class wrapper

**Comment by themkat** [comment]
This should work in VSCode thanks to https://github.com/fwcd/vscode-kotlin/pull/92. (you might need to rebuild the project before running/debugging). (debug adapter should be installed, but that happens automatically in my knowledge). Maybe we can close this issue? @fwcd 

For the people curious about the same in Emacs: If you are using lsp-mode, you can activate `lsp-kotlin-lens-mode` to see run/debug code lenses 🙂

**Comment by dvanderleij** [comment]
Hi, Haven't tested extensively as I am currently not developing any Kotlin code but the run and debug now appear in the main branch version :)
