### ISSUE TITLE
Won't Start

### ISSUE THREAD

**Issue by moncheeta** [fwcd/kotlin-language-server#333]
Whenever I run kotlin-language-server, I get an error. So, I'm unable to start it.

/sbin/kotlin-language-server: line 83: cd: /sbin/../share/kotlin/kotlin-language-server/bin/..: No such file or directory

**Comment by fwcd** [comment]
Which client are you using (e.g. VSCode, Emacs, ...)? Are you using a prebuilt version of the language server?

**Comment by Moncheeta** [comment]
I'm using a prebuilt version from the AUR and I'm using LanguageClient-neovim with neovim.

**Comment by Moncheeta** [comment]
What could be the problem?

**Comment by fwcd** [comment]
Hm, I think this might be a packaging issue, please try reporting it to the AUR maintainers of the `kotlin-language-server` package.
