### ISSUE TITLE
language extension failed to load

### ISSUE THREAD

**Issue by raid2light** [fwcd/kotlin-language-server#350]
Activating extension 'strumenta.my-kotlin-go-to-definition' failed: Cannot find module 'c:\wb\bla2\article-lsp-go-to-definition\dist\extension'
Require stack:
- c:\Users\mandric\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\mandric\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\mandric\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js.

**Comment by fwcd** [comment]
This looks like an issue with another extension (not this one). Try reporting the issue [here](https://github.com/Strumenta/article-lsp-go-to-definition).
