### ISSUE TITLE
Cannot find androidx, android

### ISSUE THREAD

**Issue by chen244** [fwcd/kotlin-language-server#356]
I use gradle,neovim and nvimlsp, use compose android.

It always cannot find the package of android and androidx. However, yesterday, when I run the application with android studio, kotlin-language-server found android and androidx. However today, I cannot make it find the package again with the same actions.So I want ask ,how to make the language server find the packages of android when use gradle and nvimlsp?

**Comment by chen244** [comment]
It works again after I ran gradle wrapper..if what I do is right? haha

**Comment by nizam-betterapp** [comment]
I think running gradlew build is necessary since that's what will download the jar files which can be used by language server for indexing. is my understanding correct?

**Comment by selfsimilar64** [comment]
> > I think running gradlew build is necessary since that's what will download the jar files which can be used by language server for indexing. is my understanding correct?
> 
> No, I finally found out that what make lsp works is that I run the android studio to build the part I need to edit.. I still cannot findout what happened.. but I finally know how to make lsp work

What setup do you have that allows the server to work and find android/androidx libraries? I have been stuck for days trying to get it to work but I always get unresolved reference errors on my android import statements.

**Comment by Decodetalkers** [comment]
> > > I think running gradlew build is necessary since that's what will download the jar files which can be used by language server for indexing. is my understanding correct?
> > 
> > No, I finally found out that what make lsp works is that I run the android studio to build the part I need to edit.. I still cannot findout what happened.. but I finally know how to make lsp work
> 
> What setup do you have that allows the server to work and find android/androidx libraries? I have been stuck for days trying to get it to work but I always get unresolved reference errors on my android import statements.

Kls will create a splite under the folder, if last time it did not work, then delete it, restart it again.

https://github.com/mykotlinlab/kotlin-language-server and you maybe can try my fork, the SQLite maybe be created failed because the old dependency of database lib, I fix that in this fork

**Comment by selfsimilar64** [comment]
> Kls will create a splite under the folder, if last time it did not work, then delete it, restart it again.
> 
> https://github.com/mykotlinlab/kotlin-language-server and you maybe can try my fork, the SQLite maybe be created failed because the old dependency of database lib, I fix that in this fork

This solved my issue, thank you so much! I also did many other things, like make sure my JAVA_HOME variable pointed towards a jdk with the same version as the one I compile against, but it was deleting the database and restarting Cursor that made it take effect.

**Comment by Decodetalkers** [comment]
> > > > > I think running gradlew build is necessary since that's what will download the jar files which can be used by language server for indexing. is my understanding correct?
> > > > 
> > > > 
> > > > No, I finally found out that what make lsp works is that I run the android studio to build the part I need to edit.. I still cannot findout what happened.. but I finally know how to make lsp work
> > > 
> > > 
> > > What setup do you have that allows the server to work and find android/androidx libraries? I have been stuck for days trying to get it to work but I always get unresolved reference errors on my android import statements.
> > 
> > Kls will create a splite under the folder, if last time it did not work, then delete it, restart it again.
> > 
> > https://github.com/mykotlinlab/kotlin-language-server and you maybe can try my fork, the SQLite maybe be created failed because the old dependency of database lib, I fix that in this fork
> 
> Thanks!!! I solved my problem through your fork of kotlin-lsp-server. Why don't you make a pr or create the lsp of yours. I can be very convenient to install lsps through mason. Now I must clone your project and compile it myself, just a little suggesion :)

I have already made lots of pr.. but they are not reviewed...
