### ISSUE TITLE
JVM Targets unable to be selected

### ISSUE THREAD

**Issue by adamgoose** [fwcd/kotlin-language-server#378]
According to [jvmTargetFrom](https://github.com/fwcd/kotlin-language-server/blob/main/server/src/main/kotlin/org/javacs/kt/compiler/Compiler.kt#L389-L402), there's no way to select JVM 16 or 17.

I was able to get a [build passing](https://github.com/adamgoose/kotlin-language-server/actions/runs/2793988009) by simply [adding](https://github.com/adamgoose/kotlin-language-server/commit/e6d84f80836489109aab6d6c819812474e519195) a `17` case.

**Comment by fwcd** [comment]
We should probably just replace our own implementation with a call to `JvmTarget.fromString` to future-proof this
