### ISSUE TITLE
Intellisense not working for external libraries in Kotlin language server

### ISSUE THREAD

**Issue by AnkitShakya538** [fwcd/kotlin-language-server#400]
For external libraries kotlin intellisense is not working. It is showing "Unresolved Reference" error.
I am trying to inject dependencies of Jackson jars to my Kotlin LSP. Can anyone suggest how we can achieve this?
![image](https://user-images.githubusercontent.com/62926180/194806285-c7820a59-3811-423b-9803-00d79c42f71e.png)

**Comment by themkat** [comment]
I guess your project is not a Maven or Gradle project, but a standalone one? One thing you can try is to resolve dependencies using a script, like described [here](https://github.com/fwcd/kotlin-language-server#figuring-out-the-dependencies).  Never tried it myself, but the implementation is still there.


If that doesn't work, please share your language server logs. I guess this is VSCode? Then you find it in the dropdown-menu in the Output-tab (where you usually have Terminal etc.):
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/5732795/194922948-234d0665-a9ed-4dce-ba91-dba0f8e4a529.png">
(the place that says Kotlin here).

**Comment by AnkitShakya538** [comment]
@themkat, thanks for your response. Yes it is a standalone project, I tried resolving dependencies using script and its working now. Closing this issue now.
