### ISSUE TITLE
LSP can't find android, androidx reference

### ISSUE THREAD

**Issue by Savuth-S** [fwcd/kotlin-language-server#411]
I'm using Nvim with this LSP and for some reason it can't recognize the android and androidx packages and I'm not sure what I'm doing wrong.

![image](https://user-images.githubusercontent.com/62723230/212474331-da5434ea-47f2-4b68-8f80-2cc4c054b10f.png)

**Comment by themkat** [comment]
Hard to say whats wrong without seeing the language server logs. My main guess is that you use Gradle, and the dependency resolution fails. As this is Android, my main guess is that you might have an error like I describe here: https://github.com/fwcd/kotlin-language-server/issues/376#issuecomment-1200469944


If you can share your language server logs (during project initialisation) that would be great :) Then we can hopefully see what the issue is in your case.

**Comment by Savuth-S** [comment]
> Hard to say whats wrong without seeing the language server logs. My main guess is that you use Gradle, and the dependency resolution fails. As this is Android, my main guess is that you might have an error like I describe here: [#376 (comment)](https://github.com/fwcd/kotlin-language-server/issues/376#issuecomment-1200469944)
> 
> If you can share your language server logs (during project initialisation) that would be great :) Then we can hopefully see what the issue is in your case.

Heres the log, ill be checking the thread you mentioned. thank you.

[lsp.log](https://github.com/fwcd/kotlin-language-server/files/10435633/lsp.log)

**Comment by Savuth-S** [comment]
After reading it I've figured out its probably my java version, however I do have JAVA 11 installed, and I already tried changing the environment variable and adding the bin to the path but LSP still wont take, I even uninstalled java 19 and still refuses to use java 11. Not sure if I'm doing something wrong

**Comment by Savuth-S** [comment]
Yes that was it, it got fixed after setting the env to the java 11 on the lsp setup in my .vimrc

![image](https://user-images.githubusercontent.com/62723230/212931858-6dee5ed8-074a-450e-91b4-474654897534.png)

**Comment by fmorroni** [comment]
Hi, I'm having this same issue but it wasn't fixed by adding the `cmd_env` setup option. I'm trying to work on a small android project but I get unresolved reference errors everywhere.
Any idea what else could be the problem? I tried looking at the lsp logs but I could't decipher much out of it.

**Comment by BPplays** [comment]
here is a similar config i made if anyone wants to copy paste
```lua
local lspconfig = require("lspconfig")
local java_path = "java/path"

lspconfig["kotlin_language_server"].setup({
	on_attach = on_attach,
	cmd_env = {JAVA_HOME=java_path},
	root_dir = lspconfig.util.find_git_ancestor
})

```
