### ISSUE TITLE
Question about adding maintainer permissions

### ISSUE THREAD

**Issue by RenFraser** [fwcd/kotlin-language-server#418]
Hi @fwcd, @themkat, and others! 

I'm not sure where to ask this so I've made a GitHub issue. If there's a more appropriate place, please let me know so I can take the conversation there :)

I was wondering if we could add some maintainers to this repository? With an extra hand or two, the open issues and pull requests could be more manageable. I think that this would encourage more people to contribute to the project.

What do you think?

**Comment by themkat** [comment]
I'm not a maintainer, but I would love to help out if @fwcd wants me to 🙂

**Comment by fwcd** [comment]
Yes, I'd definitely be open to that. I would still like to keep the number of maintainers low for now and make sure that we're not regressing on anything, but if someone has a track record of making high quality contributions over an extended period of time (like @themkat), I'm happy to grant commit access. Always glad to see people take interest in this project!

**Comment by RenFraser** [comment]
That sounds great! 🎉

I'm happy to close out this issue but do we want to leave it open until any permissions are granted for @themkat?

**Comment by themkat** [comment]
> That sounds great! 🎉
> 
> I'm happy to close out this issue but do we want to leave it open until any permissions are granted for @themkat?

I now have access to merge PRs 🙂 Unsure about access to starting builds, rebuilding etc., but we'll notice that soon enough 🙂

**Comment by RenFraser** [comment]
Awesome thanks everyone! I'm going to close this issue.
