### ISSUE TITLE
Unify hardcoded Gradle plugin versions behind a single definition

### ISSUE THREAD

**Issue by RenFraser** [fwcd/kotlin-language-server#419]
[This PR](https://github.com/fwcd/kotlin-language-server/pull/415) introduces a TODO at the top of our root `build.gradle.kts` script to replace the hardcoded version of the Kotlin plugin with one defined as a variable. Currently we use gradle properties to specify versions.

We should investigate and find the best path forward to keep our versioning consistent and only defined in a single place. Some ideas are:

- Using a `buildSrc` file where we can store version variables.
- Applying plugins to all projects once.

We should apply this not just to our version of the kotlin plugin but to other variables, such as the Java version, defined in `gradle.properties`.

**Comment by themkat** [comment]
Reason for adding the "good first issue"-tag here is that people who are skilled in Gradle Kotlin DSL might be able to pick this up without knowing too much of the Language Server itself 🙂

**Comment by RenFraser** [comment]
We could consider two ways of doing this. I think both are considered best practice.

- platform project
- dependency versions catalog

## Platform Project

Instead of specifying the dependencies with their version, such as:

```kotlin
dependencies {
    implementation(project(":data-model"))
    implementation("org.apache.commons:commons-lang3:3.12.0")
    implementation("org.slf4j:slf4j-api:1.7.3")
}
```

In the root `settings.gradle.kts`, we could add

```kotlin
dependencyResolutionManagement {

    // add this
    includeBuild("gradle/platform")
}
```

In this example, we use the `rootDir/gradle/platform/build.gradle.kts` file to define the platform depenedencies.

```kotlin
plugins {
    id("java-platform")
}

group = "com.example"

javaPlatform.allowDependencies()

// just some example libs with their versions
dependencies.constraints {
    api("org.apache.commons:commons-lang3:3.12.0")
    api("org.slf4j:slf4j-api:1.7.36")
    api("org.slf4j:slf4j-simple:1.7.36")
}
```

and then to include these dependency versions, we could specify it in each project/subproject’s `build.gradle.kts` file that needs it.

```kotlin
plugins {
    id("my-java-library")
}

dependencies {

    implementation(platform("com.example:platform"))

    implementation(project(":data-model"))
    implementation("org.apache.commons:commons-lang3")
    implementation("org.slf4j:slf4j-api")
}
```

## Dependency Versions Catalog

We could instead add a `libs.versions.toml` file to the Gradle directory (`rootDir/gradle`). Gradle will automatically detect it.

```toml
[libraries]
commons-lang = "org.apache.commons:commons-lang3:3.12.0"
slf4j-api = "org.slf4j:slf4j-api:1.7.36"
slf4j-simple = "org.slf4j:slf4j-simple:1.7.36"
```

and then when we want to use the dependencies in the build scripts, just do the following:

```kotlin
dependencies {

    implementation(platform("com.example:platform"))

    implementation(project(":data-model"))
    implementation(libs.commons.lang)
    implementation(libs.slf4j.api)
}
```
