### ISSUE TITLE
Create a new release tag

### ISSUE THREAD

**Issue by AdMorgado** [fwcd/kotlin-language-server#438]
I propose creating a new release tag.
A lot of new functionalities have been added to consider making a new release.
LSP package managers like Neovim's Mason still use version 1.3.1. It'd be nice to help developers use a recent and stable versioned release.

**Comment by RenFraser** [comment]
There's an existing issue to bump the patch version on each commit to the main branch: #428 

This should be addressed when #433 is merged. :)

**Comment by themkat** [comment]
New release was created last night by @fwcd  😄 There have been some discussion relating to the automatic releasing as well, and you can read more about that in the #433 PR. Probably not going to happen in the very near future, but it's an open discussion 🙂 


Closing this as a new release have been made. Hopefully it won't be a year untill next time. If we continue doing it manually, I hope we can at least get one every 3 months if there are new code that is merged 🙂
