### ISSUE TITLE
Feature request- Support for LSP inlay hints?

### ISSUE THREAD

**Issue by weilbith** [fwcd/kotlin-language-server#473]
Hey 👋 
Thanks for your great work here!
I was wondering if there is any plan or agenda to implement the inlay hint provider of the language server protocol. I find them extremely useful in other languages and I’m missing them quite often while writing Kotlin. 
a repository search for `inlay` left no results, so I just open this issue. 
Thanks for any insights.

**Comment by themkat** [comment]
@fwcd , seems like people want a new release with the inlay hints stuff. Would it be possible to make a release in the near future? 🙂
