### ISSUE TITLE
Problems with launching server as jar file. 

### ISSUE THREAD

**Issue by D0zee** [fwcd/kotlin-language-server#479]
Hello everyone! I'm contributing in eclipse buildship and trying to add support of kts scripts in eclipse. I decided to use kotlin-language-server in my project. I have eclipse client (eclipse itself) and this repo. I need to run kotlin-language-server as jar file. I use for it [this class](https://pastebin.com/E3xuysPs). 

But main issue is concluded in that kotlin-language-server which I take from build/libs behaves wrongly. I tried to launch one with `java -jar kotlin-language-server-1.3.4.jar` command, but I had strange error `no main manifest attribute, in kotlin-language-server-1.3.4.jar`.  I added manifest locally in build.gradle.kts, tried to pack language-server via `shadowJar` task, but no one method didn't lead me to the success. Please help me, because from that depends on result of my project. If you have possibility to investigate this problem with me in online meeting I am glad to call in any time.

**Comment by AlexisDiaz299** [comment]
how did you solve it, i have the same error but when I run the code in visual studio code

**Comment by D0zee** [comment]
@AlexisDiaz299 to be honest I already not remember, but it was a nightmare. It seemed I chose different way and denied this one.
