### ISSUE TITLE
language server won`t start after update gradle from 8.5 to 8.6

### ISSUE THREAD

**Issue by curtishd** [fwcd/kotlin-language-server#555]
I love using kotlin in neovim and I have used the kotlin-language-server for a few days. However, It seems like the language server is a little bit buggy. Sometimes, the language server provide wrong syntax hints, packages displaced in wrong places and so on.

![屏幕截图 2024-02-04 205816](https://github.com/fwcd/kotlin-language-server/assets/131777542/7eea4761-750a-46c2-9fe1-0471c5e0a744)
![屏幕截图 2024-02-04 205851](https://github.com/fwcd/kotlin-language-server/assets/131777542/5244ea8a-5e2c-486a-acfa-a886682f52b4)

**Comment by rafgugi** [comment]
how do you fix the problem @curtishd ?

**Comment by curtishd** [comment]
It`s a little weird. After I tried restarting the language service a few times, the problem went away.
