### ISSUE TITLE
Issue in running language server for neo vim chad using mason.nvim and lspconfig

### ISSUE THREAD

**Issue by FalconSlayer51** [fwcd/kotlin-language-server#577]
Iam facing this error how can i fix it?
**.neovim/nvim-win64/share/nvim/runtime/lua/vim/lsp/rpc.lua:800: Spawning language server with cmd: `{ "kotlin-language-server.bat" }` failed. The language server is either not installed, missing from PATH, or not executable.**

![WhatsApp Image 2024-06-02 at 7 09 54 PM](https://github.com/fwcd/kotlin-language-server/assets/108854849/0465df81-87b4-4650-bb6d-fc70d23d8c67)

**This is what the editor shows**

![WhatsApp Image 2024-06-02 at 7 12 31 PM](https://github.com/fwcd/kotlin-language-server/assets/108854849/65420b4c-1a34-4bde-b702-1739a0e6fb66)
**This is my Lsp status**

![image](https://github.com/fwcd/kotlin-language-server/assets/108854849/b043a4d0-e3bd-409e-b375-817cb638cb56)
please help me to solve this

**Comment by AlexandrosAlexiou** [comment]
Try to pass the  `cmd = { 'kotlin-language-server' },` with the absolute path for the kotlin-language-server.bat in your system.

**Comment by FalconSlayer51** [comment]
Thank you @AlexandrosAlexiou that worked!, passing absolute path of `kotlin-langauge-server.bat`.
