### ISSUE TITLE
Settings not taken into account

### ISSUE THREAD

**Issue by greg0ire** [fwcd/kotlin-language-server#591]
I can see this error on some lines:

`Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option [INLINE_FROM_HIGHER_PLATFORM]`

I've seen https://github.com/fwcd/kotlin-language-server/issues/72, so I tried to fix it like this:

```lua
require("mason-lspconfig").setup_handlers {
    function (server_name) -- default handler (optional)
      if server_name == "kotlin_language_server" then
        require("lspconfig")["kotlin_language_server"].setup {
          on_attach=custom_lsp_attach,
          capabilities = require('cmp_nvim_lsp').default_capabilities(),
          settings = {
            kotlin = {
              compiler = {
                jvm = {
                  target = "11"
                }
              }
            }
          }
        }
      end
      require("lspconfig")[server_name].setup {
        on_attach=custom_lsp_attach,
        capabilities = require('cmp_nvim_lsp').default_capabilities()
      }
    end,
}
```

That does not seem to have any effect. How do I troubleshoot this?

**Comment by fwcd** [comment]
Could you test if it works in VSCode? Just to rule out that it's not an editor/client-specific issue.

**Comment by greg0ire** [comment]
I am unfamiliar with VS Code but I installed it (`pacman -S code`), and then I installed [this](https://marketplace.visualstudio.com/items?itemName=fwcd.kotlin), but I don't have the `INLINE_FROM_HIGHER_PLATFORM`. Instead, I have a lot of `UNRESOLVED_REFERENCE`, for types that come from dependencies it seems.

**Comment by fwcd** [comment]
Then the language server may have trouble finding your dependencies. Try a vanilla Gradle or Maven project, if that works, try finding the differences to your project.

**Comment by greg0ire** [comment]
Ah I just saw that the page for the extension mentions that it must be a Maven or Gradle project. I'm using Gradle, but I guess I must also install a Gradle extension for vscode? I'm installing the "Gradle for Java" extension

**Comment by fwcd** [comment]
In principle Kotlin should suffice

**Comment by greg0ire** [comment]
I'll try with https://github.com/fwcd/kotlin-quick-start then

Step 1: finding the right openjdk version for it. It does not seem to be openjdk-21:

```
General error during conversion: Unsupported class file major version 65
```

**Comment by greg0ire** [comment]
Changing the setting VSCode fixes the issue, so it would seem the issue is Neovim-specific. It would be great if there was a way for me to see what settings Neovim sends to kotlin-language-server.

**Comment by greg0ire** [comment]
OK… I am stupid :facepalm:

```diff
 require("mason-lspconfig").setup_handlers {
     function (server_name) -- default handler (optional)
       if server_name == "kotlin_language_server" then
         require("lspconfig")["kotlin_language_server"].setup {
           on_attach=custom_lsp_attach,
           capabilities = require('cmp_nvim_lsp').default_capabilities(),
           settings = {
             kotlin = {
               compiler = {
                 jvm = {
                   target = "11"
                 }
               }
             }
           }
         }
+          return
       end
       require("lspconfig")[server_name].setup {
         on_attach=custom_lsp_attach,
         capabilities = require('cmp_nvim_lsp').default_capabilities()
       }
     end,
 }
```

Thanks for your answers, and great work with this LSP.

**Comment by fwcd** [comment]
Glad to hear you fixed it!
