### ISSUE TITLE
Use kotlin compiler analysis API for LSP server

### ISSUE THREAD

**Issue by amgdev9** [fwcd/kotlin-language-server#596]
I didnt look much on it but appartently there is a new analysis API included in the K2 compiler built on top of the internal compiler APIs which I presume this LSP is using. This analysis API, according to jetbrains, is viable to develop a kotlin LSP: https://github.com/JetBrains/kotlin/blob/master/docs/analysis/analysis-api/analysis-api.md

Just wanted to raise awareness of this possibility because if this approach is more high level than the current one we can lower the maintenance needed for this LSP, as well as fixing some bugs because of using lower level APIs

cc @fwcd

**Comment by fwcd** [comment]
Yes, this is already tracked by #289
