### ISSUE TITLE
Neovim setup generated sources

### ISSUE THREAD

**Issue by auryn31** [fwcd/kotlin-language-server#601]
Hey their,

thank you a lot for your work!!
I am using the kotlin language server and love to use neovim for further coding. But somehow the language server does not detect generated java files from openapi
It works just fine in intellij, so the linking in maven seems correct. But somehow the language server cannot resolve the java file/package.
It just doesnt find it.
The java files are located in 
`target/generated-sources/src/java`
Is it possible to recognize these?

Thank you for your support

**Comment by AlexandrosAlexiou** [comment]
I would like this feature as well, can we maybe have some pointers on how to implement this?
I would be available to create an MR, but I need some info to understand where to start from.

Pinging @fwcd, in case you have some time to give some pointers it would be great!
Thanks for you work!

**Comment by ikezedev** [comment]
The LSP ignores everything listed here https://github.com/kotlin-community-tools/kotlin-language-server/blob/main/shared/src/main/kotlin/org/javacs/kt/SourceExclusions.kt#L16-L20.

To work around this, set this in gradle.properties
```
buildDir=build_dir #sth else that is not ignore and make sure to add it to .gitignore
```

Rebuild and  restart the lsp/extension host for the changes to be picked up

**Comment by auryn31** [comment]
Nice, thank you a lot. Will give it a try and see if i get it running :D
