### ISSUE TITLE
LSP doesn't work in neovim completely

### ISSUE THREAD

**Issue by Toni500github** [fwcd/kotlin-language-server#602]
I have installed `kotlin-language-server` through mason and it works, but the only thing that works are only keywords snippets. syntax errors, warnings, function autocompletition, nothing else works
![image](https://github.com/user-attachments/assets/8a53a20c-6e8b-42b6-8874-9d25298f8f67)

**Comment by Toni500github** [comment]
![image](https://github.com/user-attachments/assets/ee260a1f-3794-4971-a283-61b436e46e3f)
![image](https://github.com/user-attachments/assets/f53d6ba5-c0fe-4274-9196-1bbf207f8c74)

**Comment by Dogacel** [comment]
I figured out you need some kind of gradle / maven file in your root directory to register current file to the language server.

I.e. create `settings.gradle.kts` with a sample content in your root and retry.

**Comment by Toni500github** [comment]
ah, I forgot about this issue lol.

Yeah you need to create a gradle file in your project root or use a gradle template. It was working when I was modifying my android application code through lunarvim
