### ISSUE TITLE
Using kotlin language server with neovim

### ISSUE THREAD

**Issue by vushu** [fwcd/kotlin-language-server#91]
Is there a way to use this language server with neovim?
I tried with https://github.com/autozimu/LanguageClient-neovim, but with no success.

**Comment by fwcd** [comment]
Sure, that should be possible as with any language client (I am not very familiar with neovim).

Just clone this repository and build the language server by running `./gradlew installDist` (see [`BUILDING.md`](https://github.com/fwcd/KotlinLanguageServer/blob/master/BUILDING.md) for more details). The executable start script will be located in `build/install/kotlin-language-server/bin/`, ready to be integrated into neovim.

Feel free to ask if you have any questions.

**Comment by ukch** [comment]
@vushu I am (more or less) having success using [coc](https://github.com/neoclide/coc.nvim) instead of `LanguageClient-neovim`. If you keep having problems, give coc a try instead.

**Comment by wikoion** [comment]
I've managed to get it working with vim and [coc](https://github.com/neoclide/coc.nvim), add your coc-settings.json if you need help with getting it working

**Comment by fwcd** [comment]
I have added usage instructions for `LanguageClient-neovim` [here](https://github.com/fwcd/KotlinLanguageServer/tree/master/editors#vim) and they seem to work fine using Vim 8:

![grafik](https://user-images.githubusercontent.com/30873659/62430627-694c7b80-b71f-11e9-8502-400b1fe8318f.png)

**Comment by wikoion** [comment]
> I have added usage instructions for `LanguageClient-neovim` [here](https://github.com/fwcd/KotlinLanguageServer/tree/master/editors#vim) and they seem to work fine using Vim 8:
> 
> ![grafik](https://user-images.githubusercontent.com/30873659/62430627-694c7b80-b71f-11e9-8502-400b1fe8318f.png)

I can write up instructions for [coc-nvim](https://github.com/neoclide/coc.nvim) as well if you want to add them to that page?

**Comment by fwcd** [comment]
@wikoion Yes sure, could you do that in a PR?

**Comment by fwcd** [comment]
Closing this issue since we have instructions both for `LanguageClient-neovim` as well as for `coc.nvim`.
